# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#親
lady = Category.create(name: "レディース")
mens = Category.create(name: "メンズ")
babykids = Category.create(name: "ベビー・キッズ")
interior = Category.create(name: "インテリア・住まい・小物")
bookgame = Category.create(name: "本・音楽・ゲーム")
toy = Category.create(name: "おもちゃ・ホビー・グッヅ")
cosme = Category.create(name: "コスメ・香水・美容")
homeappliance = Category.create(name: "家電・スマホ・カメラ")
sports = Category.create(name: "スポーツ・レジャー")
handmade = Category.create(name: "ハンドメイド")
ticket = Category.create(name: "チケット")
automobile = Category.create(name: "自動車・オートバイ")
other = Category.create(name: "その他")
#子
lady_tops = lady.children.create(name: "トップス")
lady_jacket = lady.children.create(name: "ジャケット/アウター")
lady_pants = lady.children.create(name: "パンツ")
lady_skirt = lady.children.create(name: "スカート")
lady_onepiece = lady.children.create(name: "ワンピース")
lady_shoes = lady.children.create(name: "靴")
lady_pajamas = lady.children.create(name: "ルームウェア/パジャマ")
lady_hat = lady.children.create(name: "帽子")
lady_bag = lady.children.create(name: "バッグ")
lady_accessories = lady.children.create(name: "アクセサリー")
lady_hairaccessory = lady.children.create(name: "ヘアアクセサリー")
lady_accessory = lady.children.create(name: "小物")
lady_clock = lady.children.create(name: "時計")
lady_wig = lady.children.create(name: "ウィッグ/エクステ")
lady_yukata = lady.children.create(name: "浴衣/水着")
lady_suit = lady.children.create(name: "スーツ/フォーマル/ドレス")
lady_maternity = lady.children.create(name: "マタニティ")
lady_other = lady.children.create(name: "その他")

mens_tops = mens.children.create(name: "トップス")
mens_jacket = mens.children.create(name: "ジャケット/アウター")
mens_pants = mens.children.create(name: "パンツ")
mens_shoes = mens.children.create(name: "靴")
mens_bag = mens.children.create(name: "バッグ")
mens_suit = mens.children.create(name: "スーツ")
mens_hat = mens.children.create(name: "帽子")
mens_accessories = mens.children.create(name: "アクセサリー")
mens_accessory = mens.children.create(name: "小物")
mens_clock = mens.children.create(name: "時計")
mens_swimsuit = mens.children.create(name: "水着")
mens_legwear = mens.children.create(name: "レッグウェア")
mens_underwear = mens.children.create(name: "アンダーウェア")
mens_other = mens.children.create(name: "その他")

babykids_clothesG95 = babykids.children.create(name: "ベビー服(女の子用) ~95cm")
babykids_clothesB95 = babykids.children.create(name: "ベビー服(男の子用) ~95cm")
babykids_clothesBG95 = babykids.children.create(name: "ベビー服(男女兼用) ~95cm")
babykids_clothesG100 = babykids.children.create(name: "キッズ服(女の子用) 100cm~")
babykids_clothesB100 = babykids.children.create(name: "キッズ服(男の子用) 100cm~")
babykids_clothesBG100 = babykids.children.create(name: "キッズ服(男女兼用) 100cm~")
babykids_shoes = babykids.children.create(name: "キッズ靴")
babykids_accessory = babykids.children.create(name: "子ども用ファッション小物")
babykids_diaper = babykids.children.create(name: "おむつ/トイレ/バス")
babykids_movinggoods = babykids.children.create(name: "外出/移動用品")
babykids_breastfeeding = babykids.children.create(name: "授乳/食事")
babykids_furniture = babykids.children.create(name: "ベビー家具/寝具/室内用品")
babykids_toy = babykids.children.create(name: "おもちゃ")
babykids_event = babykids.children.create(name: "行事/記念品")
babykids_other = babykids.children.create(name: "その他")

interior_kitchen = interior.children.create(name: "キッチン/食器")
interior_bed = interior.children.create(name: "ベッド/マットレス")
interior_sofa = interior.children.create(name: "ソファ/ソファベッド")
interior_chair = interior.children.create(name: "椅子/チェア")
interior_table = interior.children.create(name: "机/テーブル")
interior_storagefurniture= interior.children.create(name: "収納家具")
interior_mat = interior.children.create(name: "ラグ/カーペット/マット")
interior_curtain = interior.children.create(name: "カーテン/ブラインド")
interior_light = interior.children.create(name: "ライト/照明")
interior_bedding = interior.children.create(name: "寝具")
interior_accessories = interior.children.create(name: "インテリア小物")
interior_season = interior.children.create(name: "季節/年中行事")
interior_other = interior.children.create(name: "その他")

bookgame_books = bookgame.children.create(name: "本")
bookgame_manga = bookgame.children.create(name: "漫画")
bookgame_magazine = bookgame.children.create(name: "雑誌")
bookgame_cd = bookgame.children.create(name: "CD")
bookgame_bd = bookgame.children.create(name: "DVD/ブルーレイ")
bookgame_record = bookgame.children.create(name: "レコード")
bookgame_tvgame = bookgame.children.create(name: "テレビゲーム")

toy_hobby = toy.children.create(name: "おもちゃ")
toy_talent = toy.children.create(name: "タレントグッズ")
toy_comic = toy.children.create(name: "コミック/アニメグッズ")
toy_card = toy.children.create(name: "トレーディングカード")
toy_figure = toy.children.create(name: "フィギュア")
toy_equipment = toy.children.create(name: "楽器/器材")
toy_collection = toy.children.create(name: "コレクション")
toy_military = toy.children.create(name: "ミリタリー")
toy_art = toy.children.create(name: "美術品")
toy_artsupplies = toy.children.create(name: "アート用品")
toy_other = toy.children.create(name: "その他")

cosme_base = cosme.children.create(name: "ベースメイク")
cosme_up = cosme.children.create(name: "メイクアップ")
cosme_nail = cosme.children.create(name: "ネイルケア")
cosme_perfume = cosme.children.create(name: "香水")
cosme_skincare = cosme.children.create(name: "スキンケア/基礎化粧品")
cosme_bodycare = cosme.children.create(name: "ボディケア")
cosme_oralcare = cosme.children.create(name: "オーラルケア")
cosme_relaxation = cosme.children.create(name: "リラクゼーション")
cosme_diet = cosme.children.create(name: "ダイエット")
cosme_other = cosme.children.create(name: "その他")

homeappliance_smartphone = homeappliance.children.create(name: "スマートフォン/携帯電話")
homeappliance_accessories = homeappliance.children.create(name: "スマホアクセサリー")
homeappliance_pc = homeappliance.children.create(name: "PC/タブレット")
homeappliance_camera = homeappliance.children.create(name: "カメラ")
homeappliance_tv = homeappliance.children.create(name: "テレビ/映像機器")
homeappliance_audio = homeappliance.children.create(name: "オーディオ機器")
homeappliance_beauty = homeappliance.children.create(name: "美容/健康")
homeappliance_refrigerator = homeappliance.children.create(name: "冷暖房/空調")
homeappliance_homeappliance = homeappliance.children.create(name: "生活家電")
homeappliance_other = homeappliance.children.create(name: "その他")

sports_golf = sports.children.create(name: "ゴルフ")
sports_fishing = sports.children.create(name: "フィッシング")
sports_bicycle = sports.children.create(name: "自転車")
sports_exercise = sports.children.create(name: "トレーニング/エクササイズ")
sports_baseball = sports.children.create(name: "野球")
sports_football = sports.children.create(name: "サッカー/フットサル")
sports_tennis = sports.children.create(name: "テニス")
sports_snowboard = sports.children.create(name: "スノーボード")
sports_skiing = sports.children.create(name: "スキー")
sports_othersports = sports.children.create(name: "その他スポーツ")
sports_outdoor = sports.children.create(name: "アウトドア")
sports_other = sports.children.create(name: "その他")

handmade_accessories = handmade.children.create(name: "アクセサリー(女性用)")
handmade_fashion = handmade.children.create(name: "ファッション/小物")
handmade_clock = handmade.children.create(name: "アクセサリー/時計")
handmade_dailynecessities = handmade.children.create(name: "日用品/インテリア")
handmade_toy = handmade.children.create(name: "趣味/おもちゃ")
handmade_kids = handmade.children.create(name: "キッズ/ベビー")
handmade_material = handmade.children.create(name: "素材/材料")
handmade_secondarycreation = handmade.children.create(name: "二次創作物")
handmade_other = handmade.children.create(name: "その他")

ticket_music = ticket.children.create(name: "音楽")
ticket_sports = ticket.children.create(name: "スポーツ")
ticket_theater = ticket.children.create(name: "演劇/芸能")
ticket_event = ticket.children.create(name: "イベント")
ticket_movies = ticket.children.create(name: "映画")
ticket_facilityuseticket = ticket.children.create(name: "施設利用券")
ticket_discountticket = ticket.children.create(name: "優待券/割引券")
ticket_other = ticket.children.create(name: "その他")

automobile_body = automobile.children.create(name: "自動車本体")
automobile_tire = automobile.children.create(name: "自動車タイヤ/ホイール")
automobile_parts = automobile.children.create(name: "自動車パーツ")
automobile_accessories = automobile.children.create(name: "自動車アクセサリー")
automobile_motorcyclebody = automobile.children.create(name: "オートバイ車体")
automobile_motorcycleparts = automobile.children.create(name: "オートバイパーツ")
automobile_motorcycleaccessories = automobile.children.create(name: "オートバイアクセサリー")

other_bulksale = other.children.create(name: "まとめ売り")
other_food = other.children.create(name: "食品")
other_drink = other.children.create(name: "飲料/酒")
other_dailynecessities = other.children.create(name: "日用品/生活雑貨/旅行")
other_antique = other.children.create(name: "アンティーク/コレクション")
other_stationery = other.children.create(name: "文房具/事務用品")
other_officework = other.children.create(name: "事務/店舗用品")

lady_tops.children.create([{name:"Tシャツ/カットソー(半袖/袖なし)"}, {name:"Tシャツ/カットソー(七分/長袖)"},{name:"シャツ/ブラウス(半袖/袖なし)"},{name:"シャツ/ブラウス(七分/長袖)"},{name:"ポロシャツ"},{name:"キャミソール"},{name:"タンクトップ"},{name:"ホルターネック"},{name:"ニット/セーター"},{name:"チュニック"},{name:"カーディガン/ボレロ"},{name:"アンサンブル"},{name:"ベスト/ジレ"},{name:"パーカー"},{name:"トレーナー/スウェット"},{name:"ベアトップ/チューブトップ"},{name:"ジャージ"},{name:"その他"},])
lady_jacket.children.create([{name:"テーラードジャケット"},{name:"ノーカラージャケット"},{name:"Gジャン/デニムジャケット"},{name:"レザージャケット"},{name:"ダウンジャケット"},{name:"ライダースジャケット"},{name:"ミリタリージャケット"},{name:"ダウンベスト"},{name:"ジャンパー/ブルゾン"},{name:"ポンチョ"},{name:"ロングコート"},{name:"トレンチコート"},{name:"ダッフルコート"},{name:"ピーコート"},{name:"チェスターコート"},{name:"モッズコート"},{name:"スタジャン"},{name:"毛皮/ファーコート"},{name:"スプリングコート"},{name:"スカジャン"},{name:"その他"}])
lady_pants.children.create([{name:"デニム/ジーンズ"},{name:"ショートパンツ"},{name:"カジュアルパンツ"},{name:"ハーフパンツ"},{name:"チノパン"},{name:"ワークパンツ/カーゴパンツ"},{name:"クロップドパンツ"},{name:"サロペット/オーバーオール"},{name:"オールインワン"},{name:"サルエルパンツ"},{name:"ガウチョパンツ"},{name:"その他"},{name:""}])
lady_skirt.children.create([{name:"ミニスカート"},{name:"ひざ丈スカート"},{name:"ロングスカート"},{name:"ロングスカート"},{name:"その他"}])
lady_onepiece.children.create([{name:"ミニワンピース"},{name:"ひざ丈ワンピース"},{name:"ロングワンピース"},{name:"その他"}])
lady_shoes.children.create([{name:"ハイヒール/パンプス"},{name:"ブーツ"},{name:"サンダル"},{name:"スニーカー"},{name:"ミュール"},{name:"モカシン"},{name:"ローファー/革靴"},{name:"フラットシューズ/バレエシューズ"},{name:"長靴/レインシューズ"},{name:"その他"}])
lady_pajamas.children.create([{name:"パジャマ"},{name:"ルームウェア"}])
